# Generated by Django 6.0.3 on 2026-04-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_blogcategories_blogtags_departments_blogs_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog',
            new_name='category',
        ),
    ]
