# Generated by Django 6.0.3 on 2026-04-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_blog_blogs_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='position',
            new_name='review_title',
        ),
    ]
