# Generated by Django 6.0.3 on 2026-04-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(default='823-4565-13456', max_length=25)),
                ('address', models.CharField(default='Address Ta-134/A, New York, USA ', max_length=45)),
                ('email', models.EmailField(default='support@email.com', max_length=254)),
                ('support_email', models.EmailField(default='support@email.com', max_length=254)),
                ('opening_hour', models.CharField(default='Mon to Fri : 08:30 - 18:00', max_length=255)),
                ('map', models.TextField()),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
